export const LOGIN_REQUEST = "LOGIN_REQUESTS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SIGNUP_USER_REQUEST = "SIGNUP_USER_REQUESTS";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAIL = "SIGNUP_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUESTS";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";
